### ISSUE TITLE
Server.js is a mess, we need to decouple the code

### ISSUE THREAD

**Issue by decentral1se** [NomadicWeb/whereswall.ie#4]
Currently, middleware, routing and application logic are located in `server.js`. 

We need to move all routing code into seperate files in the `routes`. For each `route`, for example, the `user` route, it needs to be in a seperate file called `user.js`. Any child route of this route `user/*/*` will be included in this file. 

We need to move middleware code into a `middleware` folder. This might include a `auth.js` for authentication and a `error.js` for error handling.

Application logic should be well laid out in server.js as well as all imports.

**Comment by decentral1se** [comment]
I am modelling the routing around this blog post[[1](http://start.jcolemorrison.com/quick-tip-organizing-routes-in-large-express-4-x-apps/)].

**Comment by decentral1se** [comment]
I am currently receiving the following error:

```
module.js:340
throw err;
^
Error: Cannot find module './app/models/user.js'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/home/lwm/nomadicweb/skatedate/app/router/routes/api/api-user.js:2:15)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at module.exports (/home/lwm/nomadicweb/skatedate/app/router/index.js:4:26)

npm ERR! skatedate@1.0.0 start: `node server.js`
```

It seems that now that we have relocated each route to a seperate file, we find another problem. The `/api/xyz` routes need access to the `mongoose` connection and I currently don't know how to share it between routes without opening up a new connection per route (which sucks).

Need to solve this problem next @grady-lad
